/**
 * Generates a one-page credit-card-statement PDF with VISIBLE text, using
 * hand-assembled PDF bytes — no PDF-writing dependency.
 *
 * Pattern reference: `minimalPdf()` in src/scanner/pdf.test.ts builds a valid
 * empty PDF (Catalog/Pages/Page + xref + trailer). This script extends that
 * technique with two more objects: a /Font resource (Helvetica, WinAnsi) and
 * a content stream that paints text via BT/Tf/Td/Tj/ET operators.
 *
 * All amounts/dates below are constants, so the output is byte-for-byte
 * deterministic across runs (before optional encryption).
 *
 * Usage:
 *   npx tsx examples/corgi-agent/generate-statement.ts <output.pdf> [--encrypt <password>]
 *
 * The script ends with a self-check: it opens the PDF it just wrote with
 * mupdf, confirms it has exactly one page, and confirms the extracted page
 * text contains "MOHO BANK". Prints OK/FAIL and exits non-zero on FAIL.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

// --- card statement content ---------------------------------------------------
// MOHO BANK is not affiliated with any real financial institution; this
// statement's content is generated by this example.

const BANK_NAME = "MOHO BANK - CARD STATEMENT (BILLED: JUN 26)";
const HOLDER_LINE = "Card holder: C. MOHO          Card number: 4642 11XX XXXX 8929";
const META_LINE =
  "Statement date: 30 Jun 26     Payment due date: 15 Jul 26     Points balance: 12,450";
const TABLE_HEADER = "TRANS DATE   POSTED DATE   DESCRIPTION                          AMOUNT";

/** Balance carried over from the previous statement (constant, for determinism). */
const PREVIOUS_BALANCE = 950.0;

interface TxRow {
  transDate: string; // DD/MM/YYYY — when the money moved
  postedDate: string; // DD/MM/YYYY — when the bank posted it
  description: string;
  amount: number; // signed: positive = charge, negative = refund / card payment
}

// Plausible corgi-owner card charges in THB, Gregorian dates within the billed
// period. Includes a refund row and the card-payment row (both negative) so an
// agent must flip direction instead of sending negative amounts.
const TRANSACTIONS: TxRow[] = [
  { transDate: "02/06/2026", postedDate: "03/06/2026", description: "PET PARADISE DOG FOOD", amount: 1290.0 },
  { transDate: "05/06/2026", postedDate: "06/06/2026", description: "THONGLOR PET HOSPITAL", amount: 2450.0 },
  { transDate: "08/06/2026", postedDate: "08/06/2026", description: "GRAB RIDE", amount: 127.0 },
  { transDate: "10/06/2026", postedDate: "11/06/2026", description: "GRAB RIDE", amount: -127.0 },
  { transDate: "12/06/2026", postedDate: "13/06/2026", description: "HAPPY PAWS GROOMING", amount: 850.0 },
  { transDate: "16/06/2026", postedDate: "16/06/2026", description: "PAYMENT VIA MOHO APP", amount: -950.0 },
  { transDate: "18/06/2026", postedDate: "19/06/2026", description: "7-ELEVEN", amount: 189.5 },
  { transDate: "22/06/2026", postedDate: "22/06/2026", description: "PET INSURANCE PREMIUM", amount: 690.0 },
  { transDate: "25/06/2026", postedDate: "25/06/2026", description: "NETFLIX", amount: 419.0 },
  { transDate: "28/06/2026", postedDate: "29/06/2026", description: "CHATUCHAK TREATS AND TOYS", amount: 345.0 },
];

function fmt(n: number): string {
  return n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

/**
 * Builds the plain-text lines of the statement, one line per array entry.
 * Column alignment is monospaced-ish via manual space padding (Helvetica is
 * proportional, so this is approximate, not pixel-perfect) — one Tj per line.
 */
function buildLines(): string[] {
  const lines: string[] = [BANK_NAME, HOLDER_LINE, META_LINE, "", TABLE_HEADER];
  let totalDue = PREVIOUS_BALANCE;
  for (const tx of TRANSACTIONS) {
    totalDue += tx.amount;
    lines.push(
      `${tx.transDate}   ${tx.postedDate}   ${tx.description.padEnd(30)}  ` +
        `${fmt(tx.amount).padStart(12)}`,
    );
  }
  lines.push("");
  lines.push(`Previous balance: ${fmt(PREVIOUS_BALANCE)}     Total amount due: ${fmt(totalDue)}`);
  return lines;
}

/** Escapes PDF literal-string special characters: backslash and parens. */
function pdfEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

/** Builds the page content stream: one BT/ET block, one Tj per non-blank line. */
function buildContentStream(lines: string[]): string {
  const ops: string[] = ["BT", "/F1 10 Tf", "50 740 Td"];
  lines.forEach((line, i) => {
    if (i > 0) ops.push("0 -14 Td");
    if (line.length > 0) ops.push(`(${pdfEscape(line)}) Tj`);
  });
  ops.push("ET");
  return ops.join("\n") + "\n";
}

/**
 * Assembles a complete single-page PDF from hand-written objects, tracking
 * byte offsets as it goes (same technique as minimalPdf(), extended with a
 * Font object and a content-stream object).
 */
function buildPdf(lines: string[]): Buffer {
  const content = buildContentStream(lines);

  const header = "%PDF-1.4\n";
  const obj1 = "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n";
  const obj2 = "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n";
  const obj3 =
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] " +
    "/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n";
  const obj4 =
    "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica " +
    "/Encoding /WinAnsiEncoding >>\nendobj\n";
  const obj5 =
    `5 0 obj\n<< /Length ${Buffer.byteLength(content, "latin1")} >>\n` +
    `stream\n${content}endstream\nendobj\n`;

  const objects = [obj1, obj2, obj3, obj4, obj5];

  let offset = Buffer.byteLength(header, "latin1");
  const offsets: number[] = [];
  for (const obj of objects) {
    offsets.push(offset);
    offset += Buffer.byteLength(obj, "latin1");
  }
  const xrefStart = offset;

  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) {
    xref += `${String(off).padStart(10, "0")} 00000 n \n`;
  }

  const trailer =
    `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n` + `startxref\n${xrefStart}\n%%EOF\n`;

  return Buffer.from(header + objects.join("") + xref + trailer, "latin1");
}

/** Opens the generated PDF with mupdf and verifies page count + visible text. */
async function selfCheck(bytes: Buffer): Promise<boolean> {
  try {
    const mupdf = await import("mupdf");
    const doc = mupdf.Document.openDocument(bytes, "application/pdf");
    const pageCount = doc.countPages();
    if (pageCount !== 1) {
      console.error(`FAIL: expected 1 page, got ${pageCount}`);
      return false;
    }
    const page = doc.loadPage(0);
    const text = page.toStructuredText().asText();
    if (!text.includes("MOHO BANK")) {
      console.error("FAIL: extracted page text does not contain 'MOHO BANK'");
      console.error(text);
      return false;
    }
    console.log("OK: generated PDF has 1 page and contains visible text 'MOHO BANK'");
    return true;
  } catch (err) {
    console.error("FAIL:", err instanceof Error ? err.message : String(err));
    return false;
  }
}

/** Password-protects the PDF (AES-256) so the demo exercises the vault flow. */
async function encryptPdf(bytes: Buffer, password: string): Promise<Buffer> {
  const mupdf = await import("mupdf");
  const doc = mupdf.Document.openDocument(bytes, "application/pdf");
  try {
    const out = doc.saveToBuffer(
      `encrypt=aes-256,user-password=${password},owner-password=${password}`,
    );
    return Buffer.from(out.asUint8Array());
  } finally {
    doc.destroy();
  }
}

async function main(): Promise<void> {
  const outArg = process.argv[2];
  if (!outArg) {
    console.error(
      "usage: npx tsx examples/corgi-agent/generate-statement.ts <output.pdf> [--encrypt <password>]",
    );
    process.exit(1);
  }
  const outPath = resolve(outArg);
  const encryptIdx = process.argv.indexOf("--encrypt");
  const password = encryptIdx > -1 ? process.argv[encryptIdx + 1] : null;
  if (encryptIdx > -1 && !password) {
    console.error("--encrypt requires a password argument");
    process.exit(1);
  }

  const lines = buildLines();
  const pdf = buildPdf(lines);

  const ok = await selfCheck(pdf);
  if (!ok) process.exit(1);

  const outBytes = password ? await encryptPdf(pdf, password) : pdf;
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, outBytes);
  console.log(
    `wrote ${outBytes.length} bytes to ${outPath}${password ? " (password-protected)" : ""}`,
  );
}

main();
